language: cpp
compiler:
    - clang
    - gcc
env:
    - NOTHING=1
    - FULLDEBUG=1
    - TILES=1
    - TILES=1 FULLDEBUG=1
    - WEBTILES=1
    - WEBTILES=1 FULLDEBUG=1
    - USE_DGAMELAUNCH=1
    - USE_DGAMELAUNCH=1 WEBTILES=1
    # - TILES=1 BUILD_ALL=1
    # - WEBTILES=1 BUILD_ALL=1
git:
    submodules: false
install: perl .travis/deps.pl
script: perl .travis/build.pl
notifications:
#    email:
#        - crawl-ref-commits@lists.sourceforge.net
    irc:
        channels: "chat.freenode.net##crawl-dev"
        on_success: change
        on_failure: always
        use_notice: true
