language: cpp
compiler:
    - clang
    - gcc
env:
    - NOTHING=1
    - FULLDEBUG=1
    - USE_DGAMELAUNCH=1
    - USE_DGAMELAUNCH=1 FULLDEBUG=1
    - TILES=1
    - TILES=1 FULLDEBUG=1
    - WEBTILES=1
    - WEBTILES=1 FULLDEBUG=1
    - USE_DGAMELAUNCH=1 WEBTILES=1
    - USE_DGAMELAUNCH=1 WEBTILES=1 FULLDEBUG=1
    - BUILD_ALL=1
    - TILES=1 BUILD_ALL=1
    - WEBTILES=1 BUILD_ALL=1
git:
    submodules: false
install: perl .travis/deps.pl
script:
    - perl .travis/build.pl
    - ls crawl-ref/source/morgues/*.txt | xargs cat
notifications:
#    email:
#        - crawl-ref-commits@lists.sourceforge.net
    irc:
        channels: "chat.freenode.net##crawl-dev"
        on_success: change
        use_notice: true
